name: Format
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        # Note that we explicitly specify ${{ github.head_ref }} in the checkout Action.
        # This is required in order to work with the pull_request event (or any other non-push event).
        with:
          # documentation says we need to add this for security reasons
          # https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file
          token: ${{ secrets.PAT }}
          ref: ${{ github.head_ref }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies with npm
        run: npm ci

      - name: Run prettier
        run: npm run prettier

      - name: Commit changes with prettier
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply formatting changes with prettier
          branch: ${{ github.head_ref }}

